spring.application.name = T7BE
server.port=8080

# Elasticsearch production environment configuration
elasticsearch.host=es-cluster-eck-v901-es-http.elastic.svc.cluster.local
elasticsearch.port=9200
elasticsearch.protocol=https
elasticsearch.use-ssl=true
elasticsearch.username=elastic
elasticsearch.password=385n1Y9ROgnjo666oHt9CMu4
elasticsearch.api-key=
elasticsearch.use-api-key=false
elasticsearch.index-name=all_content_processed_vectorized_v3

# Disable Spring Boot's Elasticsearch automatic configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchRestClientAutoConfiguration 