apiVersion: v1
kind: Service
metadata:
  name: kibana-kibana
  namespace: elastic
spec:
  type: ClusterIP
  selector:
    kibana.k8s.elastic.co/name: "kibana-eck-v901"
  ports:
    - name: http
      port: 5601
      targetPort: 5601
      protocol: TCP
